### ISSUE TITLE
OutPut elasticsearch Configuration setting error

### ISSUE THREAD

**Issue by 760515805** [fluent/fluentbit-operator#180]
My profile
![image](https://user-images.githubusercontent.com/16426260/144699087-e00dc9c4-4a56-47c3-88a8-3def10bc1bd2.png)
Generated configuration file
![image](https://user-images.githubusercontent.com/16426260/144699100-fef8d0ac-5f45-4048-9167-23800f7b98c7.png)

**Comment by wenchajun** [comment]
This is a known bug that has been fixed. Please see https://github.com/fluent/fluentbit-operator/pull/160.

**Comment by 760515805** [comment]
> This is a known bug that has been fixed. Please see #160.

Is there a fix in the latest version 0.12.0? I upgraded and the bug is still there

**Comment by wenchajun** [comment]
> > This is a known bug that has been fixed. Please see #160.
> 
> Is there a fix in the latest version 0.12.0? I upgraded and the bug is still there

No yet, maybe you can package an image and run it yourself

**Comment by 760515805** [comment]
> > > This is a known bug that has been fixed. Please see #160.
> > 
> > 
> > Is there a fix in the latest version 0.12.0? I upgraded and the bug is still there
> 
> No yet, maybe you can package an image and run it yourself

ok thanks for your answer
